export const zh = {
    language: '语言',
    interface: '界面',
    devConsole: '开发者控制台',
    adaptDefault: '跟随默认设置',
    id: 'ID',
    cache: '缓存',
    file: '文件',
    newFile: '新建文件',
    openFile: '打开文件',
    save: '保存',
    essentials: '基本操作',
    copy: '复制',
    cut: '剪切',
    paste: '粘贴',
    pasteText: '无格式粘贴',
    undo: '撤销',
    redo: '重做',
    br: '换行符',
    find: '查找',
    replace: '替换',
    replaceAll: '全局替换',
    findAndReplace: '查找和替换',
    textFormatting: '文本格式',
    bold: '加粗',
    italic: '斜体',
    underline: '下划线',
    strike: '删除线',
    highlight: '高亮',
    code: '代码',
    link: '链接',
    subscript: '下标',
    superscript: '上标',
    paragraphFormatting: '段落格式',
    normalText: '普通文本',
    heading1: '一级标题',
    heading2: '二级标题',
    heading3: '三级标题',
    heading4: '四级标题',
    heading5: '五级标题',
    heading6: '六级标题',
    bulletList: '无序列表',
    orderedList: '有序列表',
    taskList: '任务列表',
    sinkListItem: '压沉列表项',
    liftListItem: '提升列表项',
    codeBlock: '代码块',
    blockquote: '引用块',
    horizontalRule: '分割线',
    alignL: '左对齐',
    alignR: '右对齐',
    alignC: '居中对齐',
    justify: '两端对齐',
    selection: '选区',
    selectAll: '全选',
    extendLeft: '向左扩展一个字符',
    extendRight: '向右扩展一个字符',
    extendUp: '向上扩展一行',
    extendDown: '向下扩展一行',
    cheatsheet: '快捷键列表',
    shortcuts: '快捷键',
    syntax: 'Markdown 语法',
    'placeholder-text': '文本',
    'placeholder-or': '或',
    'placeholder-space': '空格',
    'placeholder-colon': '：',
    revealInExplorer: '在资源管理器中显示',
    lastCacheTime: '最后缓存时间',
    copied: '复制成功',
    // addFavorite: '添加到收藏',
    unfavorite: '从收藏中移除',
    copyPath: '复制路径',
    openInNewPanel: '在新面板中打开',
    openInLeftPanel: '在左侧面板中打开',
    openInRightPanel: '在右侧面板中打开',
    openInTopPanel: '在顶部面板中打开',
    openInBottomPanel: '在底部面板中打开',
    refreshItem: '刷新此文件夹',
    editor: '编辑器',
    'editor-font-size': '字体大小',
    'editor-font-size-desc': '设置编辑器的默认字体大小。',
    'editor-background': '背景图案',
    'editor-background-desc': '全局设置编辑器默认背景，单个编辑器可独立配置并覆盖默认值。',
    'editor-gap-helper': '间隙辅助',
    'editor-gap-helper-desc': '设置编辑器在哪些节点类型之间显示间隙辅助工具。',
    'editor-gap-helper-allBlocks': '在所有块元素之间的间隙',
    'editor-gap-helper-noGapCursor': '仅在无法插入光标的间隙',
    'editor-gap-helper-allBlocks-desc': '例如：在两个段落之间，或标题和段落之间。',
    'editor-gap-helper-noGapCursor-desc': '例如：前后节点都是表格、代码块、分割线等。',
    'editor-bg-blank': '空白',
    'editor-bg-grid': '方格',
    'editor-bg-line': '线条',
    'editor-bg-dots': '点阵',
    'editor-bg-default': '默认',
    toc: '目录栏',
    'toc-initial-state': '初始状态',
    'toc-initial-state-desc': '设置新标签的目录栏的初始状态为展开或收起。',
    'toc-state-expanded': '展开',
    'toc-state-collapsed': '收起',
    'toc-default-mode': '默认模式',
    'toc-default-mode-desc': '设置新标签的目录栏在展开状态时的默认模式。',
    'toc-mode-content': '内容模式',
    'toc-mode-outline': '略图模式',
    'toc-mode-content-desc': '目录条目为标题内容。',
    'toc-mode-outline-desc': '目录条目为文档抽象大纲，具体样式由主题决定，通常表现为各标题层级对应不同长短、色彩的线条或胶囊样式。',
    'toc-mode-toggle': '切换模式',
    'toc-add-indexes': '添加索引',
    'toc-add-indexes-desc': '为每一层级标题添加从 1 开始计数至 n 的索引号。',
    'toc-overflow-behavior': '溢出处理',
    'toc-overflow-behavior-desc': '设置在标题内容超出可见区域时的处理方式。',
    'toc-overflow-auto': '自动',
    'toc-overflow-wrap': '换行',
    'toc-overflow-clip': '裁剪',
    'toc-outline-width': '宽度',
    'toc-outline-width-desc': '设置在此模式下目录栏的最大宽度，一般最大层级标题的宽度等同于此值，依层级递减。',
    statusbar: '状态栏',
    'statusbar-show-cachedTime': '显示缓存时间',
    'statusbar-show-cachedTime-desc': '对于已修改的文件，全局设置是否在状态栏显示最后缓存时间，每个编辑器可独立配置。',
    'statusbar-show-textCount': '显示文本数',
    'statusbar-show-textCount-desc': '全局设置是否在状态栏显示字数和词数，每个编辑器可独立配置。',
    'statusbar-chars': '字数',
    'statusbar-show-chars': '显示字数',
    'statusbar-words': '词数',
    'statusbar-show-words': '显示词数',
    copyright: '保留所有权利',
    theme: '主题',
    'theme-default': '默认主题',
    'theme-light': '浅色',
    'theme-dark': '深色',
    'theme-system': '跟随系统',
    'theme-installed': '已安装主题',
}
export const en = {
    language: 'Language',
    interface: 'Interface',
    devConsole: 'Developer Console',
    adaptDefault: 'Follow default settings',
    id: 'ID',
    cache: 'Cache',
    file: 'File',
    newFile: 'New File',
    openFile: 'Open File',
    save: 'Save',
    essentials: 'Essentials',
    copy: 'Copy',
    cut: 'Cut',
    paste: 'Paste',
    pasteText: 'Paste without formatting',
    undo: 'Undo',
    redo: 'Redo',
    br: 'Add a line break',
    find: 'Find',
    replace: 'Replace',
    replaceAll: 'Replace All',
    findAndReplace: 'Find and Replace',
    textFormatting: 'Text Formatting',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strike: 'Strike',
    highlight: 'Highlight',
    code: 'Code',
    link: 'Link',
    subscript: 'Subscript',
    superscript: 'Superscript',
    paragraphFormatting: 'Paragraph Formatting',
    normalText: 'Apply normal text style',
    heading1: 'Apply heading style 1',
    heading2: 'Apply heading style 2',
    heading3: 'Apply heading style 3',
    heading4: 'Apply heading style 4',
    heading5: 'Apply heading style 5',
    heading6: 'Apply heading style 6',
    bulletList: 'Bullet list',
    orderedList: 'Ordered list',
    taskList: 'Task list',
    sinkListItem: 'Sink list item',
    liftListItem: 'Lift list item',
    codeBlock: 'Code block',
    blockquote: 'Blockquote',
    horizontalRule: 'Horizontal rule',
    alignL: 'Left align',
    alignR: 'Right align',
    alignC: 'Center align',
    justify: 'Justify',
    selection: 'Text Selection',
    selectAll: 'Select All',
    extendLeft: 'Extend selection one character to left',
    extendRight: 'Extend selection one character to right',
    extendUp: 'Extend selection one line up',
    extendDown: 'Extend selection one line down',
    cheatsheet: 'Cheheat Sheet',
    shortcuts: 'Shortcuts',
    syntax: 'Syntax',
    'placeholder-text': 'text',
    'placeholder-or': 'or',
    'placeholder-space': 'space',
    'placeholder-colon': ':\u00A0',
    revealInExplorer: 'Reveal in File Explorer',
    lastCacheTime: 'Last Cached Time',
    copied: 'Copy successful',
    unfavorite: 'Remove from Favorites',
    copyPath: 'Copy Path',
    openInNewPanel: 'Open in New Panel',
    openInLeftPanel: 'Open in Left Panel',
    openInRightPanel: 'Open in Right Panel',
    openInTopPanel: 'Open in Top Panel',
    openInBottomPanel: 'Open in Bottom Panel',
    refreshItem: 'Refresh this folder',
    editor: 'Editor',
    'editor-font-size': 'Font Size',
    'editor-font-size-desc': 'Set the default font size for the editor.',
    'editor-background': 'Background Pattern',
    'editor-background-desc': 'Set the default editor background pattern globally; per-editor settings can be configured independently and will override the default.',
    'editor-gap-helper': 'Gap Helper',
    'editor-gap-helper-desc': 'Set default node types between which the editor gap helper is rendered.',
    'editor-gap-helper-allBlocks': 'All block gaps',
    'editor-gap-helper-noGapCursor': 'Non-insertable gaps',
    'editor-gap-helper-allBlocks-desc': 'E.g., gaps between two paragraphs or between a paragraph and a heading.',
    'editor-gap-helper-noGapCursor-desc': 'E.g., gaps between tables, code blocks, and horizontal rules where the cursor cannot be inserted.',
    'editor-bg-blank': 'Blank',
    'editor-bg-grid': 'Grid',
    'editor-bg-line': 'Line',
    'editor-bg-dots': 'Dots',
    'editor-bg-default': 'Default',
    toc: 'Table of Contents',
    'toc-initial-state': 'Initial State',
    'toc-initial-state-desc': 'Set the initial state of the table of contents for new tabs to expanded or collapsed.',
    'toc-state-expanded': 'Expanded',
    'toc-state-collapsed': 'Collapsed',
    'toc-default-mode': 'Default Mode',
    'toc-default-mode-desc': 'Set the default mode of the table of contents for new tabs to content or outline.',
    'toc-mode-content': 'Content Mode',
    'toc-mode-outline': 'Outline Mode',
    'toc-mode-content-desc': 'TOC items are the heading content.',
    'toc-mode-outline-desc': 'TOC items form the abstract document outline, presented as lines of varying lengths and colors, or capsule shapes per heading level.',
    'toc-mode-toggle': 'Toggle Mode',
    'toc-add-indexes': 'Add Indexes',
    'toc-add-indexes-desc': 'Add hierarchical indexes that count from 1 to n for each level.',
    'toc-overflow-behavior': 'Overflow Behavior',
    'toc-overflow-behavior-desc': 'Set the behavior when the heading content exceeds the visible area.',
    'toc-overflow-auto': 'Auto',
    'toc-overflow-wrap': 'Wrap',
    'toc-overflow-clip': 'Clip',
    'toc-overflow-clip-desc': 'When the heading content exceeds the visible area, only display the visible part.',
    'toc-overflow-wrap-desc': 'When the heading content exceeds the visible area, wrap the content.',
    'toc-overflow-behavior-auto': 'Auto',
    'toc-outline-width': 'Width',
    'toc-outline-width-desc': 'Set the maximum width of the outline mode table of contents. The width of the highest level heading is generally equal to this value, and the width decreases with each level.',
    statusbar: 'Status Bar',
    'statusbar-show-cachedTime': 'Show cached time',
    'statusbar-show-cachedTime-desc': 'For modified files, set whether to show the cached time in the status bar globally; per-editor settings can be configured independently and will override the default.',
    'statusbar-show-textCount': 'Show text count',
    'statusbar-show-textCount-desc': 'Set whether to show the character count and word count in the status bar globally; per-editor settings can be configured independently and will override the default.',
    'statusbar-chars': 'chars',
    'statusbar-show-chars': 'Show character count',
    'statusbar-words': 'words',
    'statusbar-show-words': 'Show word count',
    copyright: 'All rights reserved.',
    theme: 'Theme',
    'theme-default': 'Default theme',
    'theme-light': 'Light',
    'theme-dark': 'Dark',
    'theme-system': 'Follow System',
    'theme-installed': 'Installed Themes',
}
